[versions]
passwordless-sample-code = "1"
passwordless-sample-name = "1.0"
passwordless-sdk = "2.0.0"

compileSdk = "35"
minSdk = "28"
targetSdk = "35"

jvmTarget = "17"

androidxCore = "1.13.1"
androidGradlePlugin = "8.6.1"
appcompat = "1.7.0"
constraintlayout = "2.1.4"
credentials = "1.2.2"
detekt = "1.23.7"
espresso-core = "3.6.1"
ext-junit = "1.2.1"
hilt = "2.52"
junit = "4.13.2"
jwtdecode = "2.0.2"
kotlin = "2.0.20"
kotlinx-coroutines-play-services = "1.9.0"
material = "1.12.0"
mockito-core = "5.13.0"
navigation = "2.8.1"
okhttp-logging-interceptor = "4.12.0"
preference-ktx = "1.2.1"
retrofit = "2.11.0"
gson = "2.11.0"
sonarqube = "5.1.0.4882"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
detekt-detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-detekt-rules = { module = "io.gitlab.arturbosch.detekt:detekt-rules-libraries", version.ref = "detekt" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
jwtdecode = { group = "com.auth0.android", name = "jwtdecode", version.ref = "jwtdecode" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines-play-services" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-play-services" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp-logging-interceptor" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp-logging-interceptor" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference-ktx" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "maven-publish" }
signing = { id = "signing" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
